spring.application.name=JobApp

spring.datasource.url=jdbc:postgresql://localhost:5432/jobapp
spring.datasource.username=sahilkumar
spring.datasource.password=basedata123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

app.jwt.secret=jobapp-interview-secret-change-later
app.jwt.expiration-seconds=86400

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL
spring.mail.password=YOUR_APP_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
